baseURL = "https://j-booker.github.io/blog/"
languageCode = "en-us"
title = "Blog"
paginate = 50

[params]
  bio = "Jonathan Booker"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
