baseURL = "https://jon.rest/"
languageCode = "en-us"
title = "jon.rest"
paginate = 50

[params]
  bio = "Jonathan Booker"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
